# General PXE configuration
boot_menu_title=PXE Boot Menu
default_option=linux
timeout=100

# Boot options (add as many as needed)
linux_label=Install Rocky Linux
linux_kernel=vmlinuz-rocky
linux_initrd=initrd.img-rocky
linux_append=ip=dhcp

arch_label=Install Arch Linux
arch_kernel=vmlinuz-arch
arch_initrd=initrd.img-arch
arch_append=ip=dhcp

