# General PXE configuration
[global]
boot_menu_title=PXE Boot Menu
default_option=linux
timeout=100

# Rocky Linux Configuration
[rocky]
label=Install Rocky Linux
base_url=https://download.rockylinux.org/pub/rocky/9.5/isos/x86_64
iso_name=Rocky-9.5-x86_64-boot.iso
kernel_path=/images/pxeboot/vmlinuz
initrd_path=/images/pxeboot/initrd.img
append=inst.stage2=https://download.rockylinux.org/pub/rocky/9.5/BaseOS/x86_64/os/

# Arch Linux Configuration
[arch]
label=Install Arch Linux
base_url=https://mirrors.edge.kernel.org/archlinux/iso/2025.03.01
iso_name=archlinux-2025.03.01-x86_64.iso
kernel_path=/arch/boot/x86_64/vmlinuz-linux
initrd_path=/arch/boot/x86_64/initramfs-linux.img
append=ip=dhcp

# Ubuntu Configuration
[ubuntu]
label=Install Ubuntu
base_url=https://releases.ubuntu.com/focal/
iso_name=ubuntu-20.04.6-desktop-amd64.iso
kernel_path=/casper/vmlinuz
initrd_path=/casper/initrd
append=ip=dhcp

